defmodule Catraca.Feature do
  use Ecto.Schema
  import Ecto.Changeset
  alias Catraca.{Rule, Feature}

  @derive {Jason.Encoder, only: [:key, :rule]}

  @primary_key {:key, :string, autogenerated: false}
  @enforce_keys [:key, :rule]
  schema "feature" do
    field(:rule, :map)
    field(:active, :boolean)
  end

  def changeset(feature, params \\ %{}) do
    feature
    |> cast(params, [:rule])
    |> validate_required([:rule])
  end

  def enabled?(%Feature{:rule => rule}, payload) do
    Rule.evaluate(rule, payload)
  end
end
